[package]
name = "proton"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4"
rand = "0.8"
image = "0.24"
typenum = "1"

tri-mesh = "0.5"
bvh = "0.6"
kd-tree = "0.4"

indicatif = "0.16"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3
